spring:
  application:
    name: HSF-Project

  datasource:
    url: jdbc:mysql://localhost:3306/hsf_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

vnp:
  base:
    payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: PRUGAA47
  hash-secret: J593OQSIWKX1D2BFO2BQ7UJIA1GTWNWQ
  return-url: http://localhost:3000/vn-pay/callback

logging:
  level:
    root: INFO
    com.hsf.hsfproject: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG

