spring:
  application:
    name: HSF-Project
  datasource:
    url: jdbc:mysql://localhost:3306/hsf_project?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  datasource:
  #    url: jdbc:sqlserver://localhost:1433;databaseName=SMK22;encrypt=false;trustServerCertificate=true
  #    username: sa
  #    password: 12345
  #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #  hibernate:
  #    dialect: org.hibernate.dialect.SQLServerDialect

  # XAMPP default MySQL user is 'root' with no password. Adjust 'username' and 'password' if you have changed them.
  web:
    resources: static-locations=classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

vnp:
  base:
    payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: PRUGAA47
  hash-secret: J593OQSIWKX1D2BFO2BQ7UJIA1GTWNWQ
  return-url: http://localhost:3000/vn-pay/callback

stripe:
  secret:
    key:
  public:
    key:
  webhook:
    key:
